name: publish

on:
  # google 的 release please 似乎触发的是 release 事件，而不是 tag 事件
  release:
    types:
      - published
      - unpublished
      - created
      - edited
      - deleted
      - prereleased
      - released
  push:
    tags:
      - "**"
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "${{github.event_name}}"
          echo "${{github.event}}"
