name: release-please
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{runner.name}}"
      # - uses: google-github-actions/release-please-action@v4
      #   with:
      #     token: ${{ secrets.PAT }}